[database.dev]
url_postgresql = "postgresql://user:secretpassword@localhost:5432/dev"
url_sqlite = "sqlite:///./test_db.sqlite"

[database.prod]
url_postgresql = "postgresql://user:secretpassword@localhost:5432/prod"
url_sqlite = "sqlite:///./db.sqlite"