[project]
name = "analytics_dashboard"
version = "1.2.0"
description = "Interactive data dashboard"
authors = ["Igor Net"]
license = "Apache-2.0"
homepage = "https://datacode.dev"
repository = "https://github.com/igornet0/analytics-dashboard"

datacode = ">=2.0.0"
entry = "test_src/main.dc"

[environment]
python = false
wasm = false
target = "native" # native | wasm
profile = "release"

[dependencies]
gram_api = "git+https://github.com/igornet0/gram_api.git"

[scripts]
start = "datacode src/main.dc"
test = "datacode test"
build = "datacode build"

[lock]
file = "dpm.lock"
checksum = true