[project]
name = "test_dpm"
version = "0.1.0"
authors = ["igornet0"]
datacode = ">=2.0.0"

[environment]
python = false
wasm = false
target = "native"
profile = "release"

[dependencies]

[lock]
file = "dpm.lock"
checksum = true

[migrations]
folder = "core/database/migrations"
table = "dc_migrations"